// <auto-generated />
using EhealthV2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EhealthV2.Migrations
{
    [DbContext(typeof(DoctorsContext))]
    [Migration("20240126144541_Add fields")]
    partial class Addfields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("EhealthV2.Models.Users.Doctors", b =>
                {
                    b.Property<int>("DocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Inami")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Organisation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DocId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DocId = 1,
                            Address = "Rue de la fusée",
                            City = "Bruxelles",
                            Email = "lody@hotmail.com",
                            FirstName = "LoDY",
                            Inami = "12345678910",
                            LastName = "La fusée",
                            Organisation = "Sans",
                            PostCode = "1000",
                            Speciality = "Cardiologue"
                        },
                        new
                        {
                            DocId = 2,
                            Address = "Rue de la tortilla",
                            City = "Bruxelles",
                            Email = "toto@gmail.com",
                            FirstName = "Toto",
                            Inami = "12345678911",
                            LastName = "La Grippe",
                            Organisation = "Sans",
                            PostCode = "1050",
                            Speciality = "Généraliste"
                        },
                        new
                        {
                            DocId = 3,
                            Address = "Rue Bara",
                            City = "Bruxelles",
                            Email = "muharen@hotmail.com",
                            FirstName = "Muharem",
                            Inami = "12345678912",
                            LastName = "Le Hacker",
                            Organisation = "Sans",
                            PostCode = "1000",
                            Speciality = "kinésithérapie"
                        },
                        new
                        {
                            DocId = 4,
                            Address = "Rue Lente",
                            City = "Laeken",
                            Email = "jp@hotmail.com",
                            FirstName = "JP",
                            Inami = "12345678913",
                            LastName = "La Tortue",
                            Organisation = "Sans",
                            PostCode = "1020",
                            Speciality = "Dentiste"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
