// <auto-generated />
using EhealthV2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EhealthV2.Migrations
{
    [DbContext(typeof(DoctorsContext))]
    partial class DoctorsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("EhealthV2.Models.Users.Doctors", b =>
                {
                    b.Property<int>("SuperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("superDoc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SuperId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            SuperId = 1,
                            DocId = 1,
                            Email = "email lody",
                            FirstName = "LoDY",
                            LastName = "rue de lody",
                            superDoc = "yes"
                        },
                        new
                        {
                            SuperId = 2,
                            DocId = 2,
                            Email = "email lloyd",
                            FirstName = "Lloyd",
                            LastName = "rue de lloyd",
                            superDoc = "yes"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
